# Changes here will be overwritten by Copier.
_commit: 0.5.0
_src_path: gh:detailobsessed/copier-uv-bleeding
author_email: ismar@gmail.com
author_fullname: Ismar Iljazovic
author_username: ichoosetoaccept
copyright_license: MIT
is_existing_project: true
project_description: Monitor Windsurf and Windsurf Next resource usage and diagnose
    problems
project_name: surfmon
project_type: package
publish_to_pypi: true
repository_namespace: detailobsessed
use_blacksmith_runners: true
use_ci: true
use_polar: false
use_semantic_release: true
