# Changes here will be overwritten by Copier.
_commit: 0.29.2
_src_path: gh:detailobsessed/copier-uv-bleeding
author_email: ismar@gmail.com
author_fullname: Ismar Iljazovic
author_username: ichoosetoaccept
cli_framework: typer
copyright_license: MIT
custom_pypi_index_url: ''
project_description: Monitor Windsurf and Windsurf Next resource usage and diagnose
    problems
project_name: surfmon
project_type: app
project_visibility: public
publish_to_pypi: true
repository_host: github.com
repository_namespace: detailobsessed
repository_provider: github.com
use_blacksmith_runners: true
use_ci: true
use_polar: false
use_semantic_release: true
