# Changes here will be overwritten by Copier.
_commit: 0.20.1
_src_path: gh:detailobsessed/copier-uv-bleeding
author_email: ismar@gmail.com
author_fullname: Ismar Iljazovic
author_username: ichoosetoaccept
copyright_license: MIT
include_template_dev_scripts: false
project_description: Monitor Windsurf and Windsurf Next resource usage and diagnose
    problems
project_name: surfmon
project_type: package
project_visibility: public
publish_to_pypi: false
repository_host: github.com
repository_namespace: detailobsessed
repository_provider: github.com
use_blacksmith_runners: true
use_ci: true
use_polar: false
use_semantic_release: true
